#!/usr/bin/python

RESPONSE_HEADER = "FSP/1.0"
RESPONSE_FOOTER = "\r\n\r\n"

RESPONSE_METHOD_HELP = "HELP" #help
RESPONSE_METHOD_INDEX = "INDX" #index
RESPONSE_METHOD_HASH = "HASH" #hash
RESPONSE_METHOD_DOWNLOAD = "DWLD" #download
RESPONSE_METHOD_ERROR = "EROR" #error
RESPONSE_METHOD_QUIT = "QUIT" #quit

INVALID_COMMAND = "Invalid command"

COMMAND_HELP = "help"  # help command
COMMAND_HELP_FLAG_1 = "commands" # get list of commands available
COMMAND_HELP_FLAG_2 = "IndexGet" # get list of shared files
COMMAND_HELP_FLAG_3 = "FileHash"
COMMAND_HELP_FLAG_4 = "FileDownload"


COMMAND_INDEX_GET = "IndexGet"
COMMAND_INDEX_GET_FLAG_1 = "shortlist"
COMMAND_INDEX_GET_FLAG_2 = "longlist"
COMMAND_INDEX_GET_FLAG_3 = "regex"


COMMAND_FILE_HASH = "FileHash"
COMMAND_FILE_HASH_FLAG_1 = "verify"
COMMAND_FILE_HASH_FLAG_2 = "checkall"

COMMAND_FILE_DOWNLOAD = "FileDownload"
COMMAND_FILE_DOWNLOAD_FLAG_1 = "TCP"
COMMAND_FILE_DOWNLOAD_FLAG_2 = "UDP"

COMMAND_QUIT = "quit"

SHARED_DIRECTORY = "SHARED DIRECTORY"

FILE_TYPE_UNKNOWN = "Unknown"
